# type: ignore
"""autoservice_manage_provided_maintenance_permission

Revision ID: c253a144a0e0
Revises: 7a2008f64b7c
Create Date: 2025-07-27 19:48:56.775096+03:00

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from advanced_alchemy.types import GUID, ORA_JSONB, DateTimeUTC, EncryptedString, EncryptedText
from alembic import op
from alembic_postgresql_enum import ColumnType, TableReference
from sqlalchemy import Text  # noqa: F401

__all__ = ["data_downgrades", "data_upgrades", "downgrade", "schema_downgrades", "schema_upgrades", "upgrade"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "c253a144a0e0"
down_revision = "7a2008f64b7c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="autoserviceuserpermissions",
        new_values=["autoservice:manage", "autoservice:manage_provided_maintenance"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="autoservice_users",
                column_name="permissions",
                column_type=ColumnType.ARRAY,
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="autoserviceuserpermissions",
        new_values=["autoservice:manage"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="autoservice_users",
                column_name="permissions",
                column_type=ColumnType.ARRAY,
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
