= Основные алгоритмы компонента products, сущности mechanic
:author: Дмитрий Панин
:email: dimitri-05@mail.ru
:revnumber: 1.0
:revdate: 17.08.2025

Документ представляет основные алгоритмы компонента **products**, сущности **mechanic** платформы **почини.онлайн**.

== Создание сущности

Данные для создания сущности:

[plantuml, mechanic-creation-data, svg]
....
@startuml
object MechanicCreationData
MechanicCreationData : name = string(length <= 150)
MechanicCreationData : description = string(length <= 1500) | null
MechanicCreationData : city = string(length <= 200)
MechanicCreationData : address = string(length <= 500) | null
MechanicCreationData : lon = float(-180 < value < 180) | null
MechanicCreationData : lat = float(-90 < value < 90) | null
MechanicCreationData : private = boolean
MechanicCreationData : mobile = boolean
@enduml
....

Алгоритм:

[plantuml, mechanic-creation, svg]
....
@startuml
actor User as "Пользователь\n(браузер или мобильное приложение)"
participant Client as "client\n(node.js)"
participant ProductsServer as "products\n(Python)"
database ProductsDB as "products DB\n(PostgreSQL)"

User --> Client : Запрос на получение страницы выбора GET/products
Client --> User : Страница выбора с вариантами:\n"Войти, как владелец ТС"\n"Войти, как механик"\n"Войти, как представитель автосервиса"
User --> Client : Выбор варианта "Войти, как механик" GET/products/mechanics/create
Client --> User : Форма для создания механика
User --> Client : Заполнение формы POST/api/v1/mechanics
Client --> ProductsServer : POST/products/api/v1/mechanics\nДанные из формы\nsession_token в cookies\nВсе headers и cookies, пришедшие от пользователя
ProductsServer --> ProductsServer : Валидация данных
ProductsServer --> ProductsServer : Валидация токена
alt Токен истек, отозван или некорректный
    ProductsServer --> Client : 401 Unauthorized
    Client --> User : Редирект на страницу логина\nGET/login?redirect_uri=https://pochini.online/products/mechanics/create
else Токен корректный
    ProductsServer --> ProductsDB : Сохранение данных о механике
    ProductsDB --> ProductsServer : Подтверждение сохранения
    ProductsServer --> Client : Данные о механике
    Client --> User : Данные о механике\nlocation (redirect_uri) https://pochini.online/products/mechanics/lk в headers
    User --> User : Сохранение данных о механике
    User --> User : Redirect по location (redirect_uri)
end
....

